# Generated by Django 4.1.3 on 2022-12-06 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsession',
            name='order',
        ),
        migrations.AddField(
            model_name='itemsession',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cart.cartsession'),
        ),
    ]
