# Generated by Django 4.1.3 on 2022-12-06 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_itemsession_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsession',
            name='craeted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemsession',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
