# Generated by Django 4.1.3 on 2022-12-06 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='order',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.paymentdetail'),
            preserve_default=False,
        ),
    ]
