# Generated by Django 4.1.3 on 2022-12-06 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_orderdetail_payment_paymentdetail_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='order.orderdetail'),
        ),
    ]
