# Generated by Django 4.1.3 on 2022-11-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_otpcode_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='phone',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
