# Generated by Django 4.1.3 on 2022-12-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_otpcode_code_alter_otpcode_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
