# Generated by Django 4.1.3 on 2023-02-28 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_defualt_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
